parameters:
  qrcode_config:
    relation_form_id: 1300 # official reserved bazar form id for relations
    default_relation_type: 'contact' # default type of relation
    default_user_form: '1' # default user form id
    visualisation_refresh_period: '30000' # in seconds

  qrcode_editable_config_params:
    - 'qrcode_config[relation_form_id]'
    - 'qrcode_config[default_relation_type]'
    - 'qrcode_config[default_user_form]'
    - 'qrcode_config[visualisation_refresh_period]'

services:
  _defaults:
    autowire: true
    public: true

  #YesWiki\Qrcode\Service\:
  #  resource: 'services/*'

  # Allows to use controllers as services
  YesWiki\Qrcode\Controller\:
    resource: 'controllers/*'